apiVersion: v1
kind: Service
metadata:
  name: {{ include "py2.fullname" . }}
  labels:
    app: py2
  {{- include "py2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.py2.type }}
  selector:
    app: py2
  {{- include "py2.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.py2.ports | toYaml | nindent 2 -}}
