---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
  namespace: mongodb
  labels:
    app.kubernetes.io/name: mongodb-exporter
#    app: mongodb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
#      app: mongodb-exporter
      app.kubernetes.io/name: mongodb-exporter
#      app: mongodb-exporter
  template:
    metadata:
      labels:
#        app: mongodb-exporter
        app.kubernetes.io/name: mongodb-exporter
#        app: mongodb-exporter
    spec:
      containers:
      - name: mongodb-exporter
#      - name: exporter
#      - name: mongodb-exporter
#        image: percona/mongodb_exporter:0.30
        image: percona/mongodb_exporter:0.39
        args:
#        - "--mongodb://ebenjamin:devops123@my-mongodb-0.my-mongodb-svc.mongodb.svc.cluster.local:27017"
        - "--mongodb://ebenjamin:devops123@my-mongodb-0.my-mongodb-svc.mongodb.svc.cluster.local:27017/admin?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.1.5"
        - "--collect-all"
        #        - --mongodb.uri=mongodb://user:password@mongodb-service-name:27017
        ports:
        - name: metrics
          containerPort: 9216
          protocol: TCP
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
#      app.kubernetes.io/name: mongodb-exporter