kubernetesClusterDomain: cluster.local
py2Gke:
  ports:
  - name: svc-port
    port: 80
    protocol: TCP
    targetPort: 5000
  py2Gke:
    image:
      repository: us-central1-docker.pkg.dev/iconic-star-416704/py-gce-build/py-gce-build
      tag: latest
  replicas: 2
  type: LoadBalancer
