#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: "eb-sa"
#  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eb-cp-app-ext-lb2
  labels:
    app: eb-cp-app-ext-lb2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eb-cp-app-ext-lb2
  template:
    metadata:
      labels:
        app: eb-cp-app-ext-lb2
    spec:
      serviceAccountName: "eb-sa"
      containers:
        - name: eb-cp-app-ext-lb2
          image: us-central1-docker.pkg.dev/iconic-star-416704/py-gce-build/py-gce-build:latest
          ports:
            - containerPort: 5000
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: eb-cp-app-ext-lb2
  namespace: "default"
  labels:
    app: eb-cp-app-ext-lb2
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  selector:
    app: eb-cp-app-ext-lb2
  type: "LoadBalancer"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eb-cp-app-ext-lb2
  annotations:
#    alb.ingress.kubernetes.io/load-balancer-name: ingress
#    alb.ingress.kubernetes.io/target-type: ip
#    alb.ingress.kubernetes.io/scheme: internet-facing
    cloud.google.com/load-balancer-type: External
spec:
  ingressClassName: cp-app
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eb-cp-app-ext-lb2
                port:
                  number: 80
