name: Build image and deploy

on:
  push:
    branches:
    - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: auth
      uses: google-github-actions/auth@v0.4.0
      with:
#        workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        workload_identity_provider: 'projects/721141404780/locations/global/workloadIdentityPools/github/providers/my-repo'
        service_account: 'service-a@iconic-star-416704.iam.gserviceaccount.com'

    - id: get-gke-credentials
      uses: google-github-actions/get-gke-credentials@v0.4.0
      with:
        cluster_name: eb-cluster
        location: us-central1-a

    - id: get-pods
      run: kubectl get pods

#    - name: deploy to gke
#      env:
#        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
#      run: |
#
#        gcloud container clusters get-credentials eb-cluster --zone us-central1-a --project $GOOGLE_PROJECT
#        kubectl apply -f helm-testing/py2.yaml