name: Access secret manager with WIF token

on:
#  workflow_dispatch
  push:
    branches:
    - 'master'

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v4

    - id: 'auth'
      name: 'Authenticate Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
#        token_format: 'access_token'
        project_id: 'iconic-star-416704'
        workload_identity_provider: 'projects/721141404780/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-actions-sa@iconic-star-416704.iam.gserviceaccount.com'
#        service_account: 'service-a@iconic-star-416704.iam.gserviceaccount.com'
#        token_format: 'access_token'
#        id_token_include_email: true

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v1

    - name: Access secret manager
      run: |
        gcloud secrets versions access "latest" --secret "eb-secret"
#      run: |-
#        curl https://secretmanager.googleapis.com/v1/projects/iconic-star-416704/secrets/eb-secret/versions/1:access \
#          --header "Authorization: Bearer ${{ steps.auth.outputs.access_token }}"

#    - name: List pods
#      env:
#        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
#      run: |
#        gcloud container clusters get-credentials eb-cluster --zone us-central1-a --project $GOOGLE_PROJECT
#        kubectl get pods

    - id: 'gcloud'
      name: Access secret manager
#      run: |-
#        curl https://secretmanager.googleapis.com/v1/projects/iconic-star-416704/secrets/eb-secret/versions/1:access \
#          --header "Authorization: Bearer ${{ steps.auth.outputs.access_token }}"
      run: |
        gcloud secrets versions access "latest" --secret "eb-secret"